# https://pnpm.io/pnpm-workspace_yaml
packages:
  - "packages/@eventual/*"
  - "packages/@eventual/integrations/*"
  - "packages/create-eventual"
  - "apps/*"
  - "apps/tests/*"
  - "apps/test-app-sst/services"
