receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 25ms

exporters:
  logging:
    loglevel: debug
  awsxray:
    index_all_attributes: true
  awsemf:
    log_group_name: /metrics/eventual
    log_stream_name: "{SERVICE_NAME}"

#enables output for traces to xray
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, awsemf]
