name: build
on:
  pull_request: {}
  workflow_call: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      CLEAN_UP_STACK: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test

  # test:
  #   needs: [build]
  #   concurrency: pr-test-${{ github.ref }}
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     id-token: write
  #   env:
  #     CI: "true"
  #     CLEAN_UP_STACK: "1"
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - name: Run tests
  #       run: pnpm test
